<a href="https://colab.research.google.com/github/mohamadfaisalbashir/Practical-Linear-Algebra/blob/main/08_Matrix_Inverse.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Matrix Inverse**

This notebook covers Matrix Inverse:
1. The Matrix Inverse
2. Computing the Inverse
3. One-Sided Inverses
4. Numerical Stability
5. Geometric Interpretation
6. Summary



In [1]:
import numpy as np
import matplotlib.pyplot as plt
from scipy import linalg

np.random.seed(42)
plt.rcParams['figure.figsize'] = (12, 8)

## **1. The Matrix Inverse**

The matrix inverse is one of the most important concepts in linear algebra. Just as the multiplicative inverse of a scalar a is 1/a (defined for all non-zero a), the matrix inverse of a square matrix A is a matrix denoted A^(-1) such that A A^(-1) = A^(-1) A = I, where I is the identity matrix.

For a square matrix A of size n by n, the inverse A^(-1) is defined such that:

A @ A^(-1) = A^(-1) @ A = I

where I is the n by n identity matrix. This definition is analogous to scalar multiplication: for a non-zero scalar a, we have a times (1/a) equals 1.

In [2]:
print('MATRIX INVERSE FUNDAMENTALS')
print('=' * 70)

# Create a simple 2x2 invertible matrix
A = np.array([[1, 2],
              [3, 4]], dtype=float)

print(f'Matrix A:')
print(A)

# Compute inverse
A_inv = np.linalg.inv(A)
print(f'\nInverse A^(-1):')
print(A_inv)

# Verify: A @ A^(-1) should equal I
result1 = A @ A_inv
print(f'\nA @ A^(-1) =')
print(result1)
print(f'Is identity: {np.allclose(result1, np.eye(2))}')

# Verify: A^(-1) @ A should equal I
result2 = A_inv @ A
print(f'\nA^(-1) @ A =')
print(result2)
print(f'Is identity: {np.allclose(result2, np.eye(2))}')

MATRIX INVERSE FUNDAMENTALS
Matrix A:
[[1. 2.]
 [3. 4.]]

Inverse A^(-1):
[[-2.   1. ]
 [ 1.5 -0.5]]

A @ A^(-1) =
[[1.0000000e+00 0.0000000e+00]
 [8.8817842e-16 1.0000000e+00]]
Is identity: True

A^(-1) @ A =
[[1.00000000e+00 0.00000000e+00]
 [1.11022302e-16 1.00000000e+00]]
Is identity: True


### Properties of the Inverse

1. **Uniqueness**: If A has an inverse, the inverse is unique.
2. **Distributive Property**: (AB)^(-1) = B^(-1) A^(-1) (note the reversed order)
3. **Transpose Property**: (A^T)^(-1) = (A^(-1))^T
4. **Scalar Property**: (cA)^(-1) = (1/c) A^(-1) for non-zero scalar c
5. **Inverse of Inverse**: (A^(-1))^(-1) = A

In [3]:
print('MATRIX INVERSE PROPERTIES')
print('=' * 70)

A = np.array([[2, 1],
              [1, 2]], dtype=float)
A_inv = np.linalg.inv(A)

print('\n1. Uniqueness - inverse is unique')
print('Verified by numpy.linalg.inv returning single solution')

print('\n2. LIVE EVIL Rule: (AB)^(-1) = B^(-1) @ A^(-1)')
B = np.array([[3, 1],
              [1, 3]], dtype=float)
AB = A @ B
AB_inv = np.linalg.inv(AB)
B_inv_A_inv = np.linalg.inv(B) @ np.linalg.inv(A)
print(f'(AB)^(-1) equals B^(-1) @ A^(-1): {np.allclose(AB_inv, B_inv_A_inv)}')

print('\n3. Transpose Property: (A^T)^(-1) = (A^(-1))^T')
A_T_inv = np.linalg.inv(A.T)
A_inv_T = A_inv.T
print(f'(A^T)^(-1) equals (A^(-1))^T: {np.allclose(A_T_inv, A_inv_T)}')

print('\n4. Scalar Property: (cA)^(-1) = (1/c) A^(-1)')
c = 2
cA_inv = np.linalg.inv(c * A)
c_inv_A_inv = (1/c) * A_inv
print(f'(2A)^(-1) equals (1/2) A^(-1): {np.allclose(cA_inv, c_inv_A_inv)}')

print('\n5. Inverse of Inverse: (A^(-1))^(-1) = A')
A_inv_inv = np.linalg.inv(A_inv)
print(f'(A^(-1))^(-1) equals A: {np.allclose(A_inv_inv, A)}')

MATRIX INVERSE PROPERTIES

1. Uniqueness - inverse is unique
Verified by numpy.linalg.inv returning single solution

2. LIVE EVIL Rule: (AB)^(-1) = B^(-1) @ A^(-1)
(AB)^(-1) equals B^(-1) @ A^(-1): True

3. Transpose Property: (A^T)^(-1) = (A^(-1))^T
(A^T)^(-1) equals (A^(-1))^T: True

4. Scalar Property: (cA)^(-1) = (1/c) A^(-1)
(2A)^(-1) equals (1/2) A^(-1): True

5. Inverse of Inverse: (A^(-1))^(-1) = A
(A^(-1))^(-1) equals A: True


## **2. Computing the Inverse**

### **2.1 Inverse of a 2x2 Matrix**

For a 2x2 matrix A = [[a, b], [c, d]], the inverse has a simple closed-form formula:

A^(-1) = (1/(ad - bc)) times [[d, -b], [-c, a]]

where ad - bc = det(A). This formula is efficient for small matrices.

In [4]:
print('INVERSE OF 2x2 MATRIX - MANUAL CALCULATION')
print('=' * 70)

A = np.array([[3, 8],
              [4, 6]], dtype=float)

print(f'Matrix A:')
print(A)

# Manual formula
a, b = 3, 8
c, d = 4, 6
det = a*d - b*c

print(f'\nDeterminant: {a}*{d} - {b}*{c} = {det}')

A_inv_manual = (1/det) * np.array([[d, -b], [-c, a]])
print(f'\nManual inverse:')
print(A_inv_manual)

A_inv_numpy = np.linalg.inv(A)
print(f'\nNumPy inverse:')
print(A_inv_numpy)

print(f'\nMatch: {np.allclose(A_inv_manual, A_inv_numpy)}')

# Verify
print(f'\nVerification: A @ A^(-1) =')
print(A @ A_inv_numpy)
print(f'Is identity: {np.allclose(A @ A_inv_numpy, np.eye(2))}')

INVERSE OF 2x2 MATRIX - MANUAL CALCULATION
Matrix A:
[[3. 8.]
 [4. 6.]]

Determinant: 3*6 - 8*4 = -14

Manual inverse:
[[-0.42857143  0.57142857]
 [ 0.28571429 -0.21428571]]

NumPy inverse:
[[-0.42857143  0.57142857]
 [ 0.28571429 -0.21428571]]

Match: True

Verification: A @ A^(-1) =
[[1. 0.]
 [0. 1.]]
Is identity: True


## **3. Numerical Stability**

### **The Condition Number**

When computing matrix inverses numerically, the condition number of a matrix determines how sensitive the computation is to rounding errors.

**Well-conditioned matrices**: Small condition number (close to 1), inverse can be computed reliably

**Ill-conditioned matrices**: Large condition number, numerical errors are amplified

In [5]:
print('CONDITION NUMBER AND NUMERICAL STABILITY')
print('=' * 70)

# Well-conditioned matrix
A_good = np.eye(3)
kappa_good = np.linalg.cond(A_good)
print(f'Identity matrix condition number: {kappa_good:.6f}')
print('Well-conditioned: Yes')

# Ill-conditioned matrix
A_bad = np.array([[1, 2],
                  [1.0001, 2.0002]], dtype=float)
kappa_bad = np.linalg.cond(A_bad)
print(f'\nNearly singular matrix condition number: {kappa_bad:.2e}')
print('Ill-conditioned: Yes')

# Diagonal matrix with varied diagonal
A_diag = np.diag([1, 100, 10000])
kappa_diag = np.linalg.cond(A_diag)
print(f'\nDiagonal matrix condition number: {kappa_diag:.2e}')
print('Well-conditioned: No')

CONDITION NUMBER AND NUMERICAL STABILITY
Identity matrix condition number: 1.000000
Well-conditioned: Yes

Nearly singular matrix condition number: inf
Ill-conditioned: Yes

Diagonal matrix condition number: 1.00e+04
Well-conditioned: No


## **Summary**

The matrix inverse A^(-1) is fundamental to linear algebra and applications in data science:

- **Definition**: A square matrix A has inverse A^(-1) iff A @ A^(-1) = I
- **Conditions**: Matrix must be square and full-rank (det(A) not equal to 0)
- **Computing**: 2x2 have formula, diagonal have trivial inverses, general use numerical algorithms
- **Stability**: Condition number determines numerical reliability
- **Applications**: Solving linear systems, geometric transformations, optimization